version: '3'
services:
  wol-go-web:
    image: zy1234567/wol-go-web:latest
    container_name: WolGoWeb
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - PORT=9090
      - KEY=false
      - USERNAME=admin
      - PASSWORD=admin
    volumes:
      - ./data:/web/data